export default {
  "login": "Dliz05",
  "id": 86371128,
  "node_id": "MDQ6VXNlcjg2MzcxMTI4",
  "avatar_url": "https://avatars.githubusercontent.com/u/86371128?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Dliz05",
  "html_url": "https://github.com/Dliz05",
  "followers_url": "https://api.github.com/users/Dliz05/followers",
  "following_url": "https://api.github.com/users/Dliz05/following{/other_user}",
  "gists_url": "https://api.github.com/users/Dliz05/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Dliz05/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Dliz05/subscriptions",
  "organizations_url": "https://api.github.com/users/Dliz05/orgs",
  "repos_url": "https://api.github.com/users/Dliz05/repos",
  "events_url": "https://api.github.com/users/Dliz05/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Dliz05/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Aliza Dixit",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 25,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2021-06-23T16:19:46Z",
  "updated_at": "2023-03-17T06:58:32Z"
}
